#!/usr/bin/env node
/**
 * `dns-doctor` — the DNS Doctor API from the terminal, every tool the MCP
 * server exposes as a command.
 *
 * `--json` prints the API response verbatim (the path for scripts and agents).
 * Exit codes: 0 nothing failing · 1 a failing verdict · 2 error, incl. every
 * transient (rate limit, 402 offer, outage) — never read 2 as a verdict.
 */

import { readFileSync, realpathSync } from "node:fs";
import { basename } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

import { ApiError, DEFAULT_API_BASE, getJson, packageVersion, postFile, postJson } from "./api.js";
import { exitCodeFor, render } from "./format.js";
import { COMMANDS, reportPath, routeFor } from "./routes.js";

const USAGE = `dns-doctor ${packageVersion()} — scan, fix and verify a domain's DNS (${DEFAULT_API_BASE})

usage: dns-doctor <command> [target] [options]

scan & fix
  scan <domain> [--fresh]              the seven-check report (persisted, or a fresh scan on a miss)
  dmarc-upgrade <domain>               the next safe DMARC policy step as a record, or why there is none
  parked <domain> --confirm-no-mail    the three-record hardening pack for a domain that sends no mail
  signup-url <domain>                  a sign-up link to hand the domain's owner for monitoring

records
  dmarc-validate "<record>"            every tag of a DMARC record checked, with the safe next step
  dmarc-generate <none|quarantine|reject> [--rua <email>] [--subdomain-policy <p>] [--strict]
  spf-count <domain | "<SPF record>">  DNS lookups against the 10-lookup limit
  spf-audit <domain>                   the SPF include tree with registration and lookup findings
  dkim <domain> --selector <s>         a DKIM selector's published key
  report-parse <file.xml|.gz|.zip>     one DMARC aggregate report as a table

live DNS
  record <domain> --kind <spf|dmarc|txt|mx|cname|a|aaaa> [--host <label>]
                                       authoritative answer beside two public caches, with TTLs
  propagation <name> [--type A] [--expect <value>]
                                       one name read from six locations on four continents
  reverse-dns <ip>                     forward-confirmed reverse DNS for a mail server address

monitoring (DNSDOCTOR_API_TOKEN required)
  alerts [--domain d] [--since t] [--before t] [--alert-type t] [--limit n]
  readiness <domain>                   enforcement readiness from aggregate-report evidence

options
  --json                               print the API response verbatim
  --version, --help

Fix records are generated by a deterministic engine and printed verbatim; a human
approves every DNS change. SPF is diagnose-only: no SPF record is ever proposed.`;

export interface Parsed {
  command: string;
  target: string | undefined;
  json: boolean;
  fresh: boolean;
  type: string;
  expect: string | undefined;
  selector: string | undefined;
  kind: string | undefined;
  host: string | undefined;
  rua: string | undefined;
  subdomainPolicy: string | undefined;
  strict: boolean;
  confirmNoMail: boolean;
  domain: string | undefined;
  since: string | undefined;
  before: string | undefined;
  alertType: string | undefined;
  limit: string | undefined;
}

const TARGETLESS = new Set(["alerts"]);

export function parse(argv: string[]): Parsed | "help" | "version" {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      json: { type: "boolean", default: false },
      fresh: { type: "boolean", default: false },
      type: { type: "string", default: "A" },
      expect: { type: "string" },
      selector: { type: "string" },
      kind: { type: "string" },
      host: { type: "string" },
      rua: { type: "string" },
      "subdomain-policy": { type: "string" },
      strict: { type: "boolean", default: false },
      "confirm-no-mail": { type: "boolean", default: false },
      domain: { type: "string" },
      since: { type: "string" },
      before: { type: "string" },
      "alert-type": { type: "string" },
      limit: { type: "string" },
      help: { type: "boolean", default: false },
      version: { type: "boolean", default: false },
    },
  });
  if (values.version) return "version";
  const [command, target] = positionals;
  if (values.help || !command || !COMMANDS.includes(command)) return "help";
  if (!target && !TARGETLESS.has(command)) return "help";
  return {
    command,
    target,
    json: values.json,
    fresh: values.fresh,
    type: values.type,
    expect: values.expect,
    selector: values.selector,
    kind: values.kind,
    host: values.host,
    rua: values.rua,
    subdomainPolicy: values["subdomain-policy"],
    strict: values.strict,
    confirmNoMail: values["confirm-no-mail"],
    domain: values.domain,
    since: values.since,
    before: values.before,
    alertType: values["alert-type"],
    limit: values.limit,
  };
}

function need(value: string | undefined, what: string): string {
  if (!value) throw new ApiError(`${what} is required — see dns-doctor --help`, null, false);
  return value;
}

function query(path: string, params: Record<string, string | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) if (value !== undefined) search.set(key, value);
  const encoded = search.toString();
  return encoded ? `${path}?${encoded}` : path;
}

/** One request per command — the endpoint's own field names, nothing renamed. */
export async function run(p: Parsed): Promise<unknown> {
  const path = (command: string): string => routeFor(command).path as string;
  const target = p.target ?? "";
  switch (p.command) {
    case "scan":
      return p.fresh ? postJson(path("scan"), { domain: target }) : getJson(reportPath(target));
    case "dmarc-upgrade":
      return postJson(path("dmarc-upgrade"), { domain: target });
    case "signup-url":
      return postJson(path("signup-url"), { domain: target });
    case "parked": {
      // The gate is the human's: only the domain's owner can assert it sends no
      // mail, and only the API decides whether the evidence permits the pack.
      if (!p.confirmNoMail) {
        throw new ApiError(
          "parked requires --confirm-no-mail: only the domain's owner can assert that it sends no mail",
          null,
          false,
        );
      }
      const body: Record<string, unknown> = { domain: target, confirm_no_mail: true };
      if (p.rua !== undefined) body.rua_email = p.rua;
      return postJson(path("parked"), body);
    }
    case "dmarc-validate":
      return postJson(path("dmarc-validate"), { record: target });
    case "dmarc-generate": {
      const body: Record<string, unknown> = { policy: target, strict_alignment: p.strict };
      if (p.rua !== undefined) body.rua_email = p.rua;
      if (p.subdomainPolicy !== undefined) body.subdomain_policy = p.subdomainPolicy;
      return postJson(path("dmarc-generate"), body);
    }
    case "spf-count":
      // A pasted record has spaces or '='; a domain has neither. No record
      // literal here — the API decides what a record is.
      return postJson(path("spf-count"), /[\s=]/.test(target.trim()) ? { record: target } : { domain: target });
    case "spf-audit":
      return postJson(path("spf-audit"), { domain: target });
    case "dkim":
      return postJson(path("dkim"), { domain: target, selector: need(p.selector, "--selector") });
    case "report-parse": {
      const route = routeFor("report-parse");
      return postFile(route.path as string, route.field as string, readFileSync(target), basename(target));
    }
    case "record": {
      const body: Record<string, unknown> = { domain: target, kind: need(p.kind, "--kind") };
      if (p.host !== undefined) body.host = p.host;
      return postJson(path("record"), body);
    }
    case "propagation": {
      const body: Record<string, unknown> = { name: target, record_type: p.type };
      if (p.expect !== undefined) body.expected_value = p.expect;
      return postJson(path("propagation"), body);
    }
    case "reverse-dns":
      return postJson(path("reverse-dns"), { ip: target });
    case "alerts":
      return getJson(query(path("alerts"), { domain: p.domain, since: p.since, before: p.before, type: p.alertType, limit: p.limit }));
    case "readiness":
      return getJson(query(path("readiness"), { domain: target }));
    default:
      throw new Error(`unknown command ${p.command}`);
  }
}

export async function main(argv: string[]): Promise<number> {
  const parsed = parse(argv);
  if (parsed === "version") {
    process.stdout.write(`${packageVersion()}\n`);
    return 0;
  }
  if (parsed === "help") {
    process.stdout.write(`${USAGE}\n`);
    return argv.includes("--help") ? 0 : 2;
  }
  try {
    const body = await run(parsed);
    process.stdout.write(`${parsed.json ? JSON.stringify(body, null, 2) : render(parsed.command, body)}\n`);
    return exitCodeFor(parsed.command, body);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    process.stderr.write(`dns-doctor: ${message}\n`);
    return 2;
  }
}

/**
 * Is this module the process entry point? Compared by REAL path: under
 * `npx dns-doctor` argv[1] is the `node_modules/.bin` symlink while the module
 * URL is the target file, and a naive string comparison silently ran nothing
 * (0.2.0 shipped that way — every npx run exited 0 with no output).
 */
export function isEntryPoint(argv1: string | undefined, moduleUrl: string): boolean {
  if (typeof argv1 !== "string" || argv1 === "") return false;
  try {
    return realpathSync(argv1) === realpathSync(fileURLToPath(moduleUrl));
  } catch {
    return false;
  }
}

if (isEntryPoint(process.argv[1], import.meta.url)) {
  main(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  });
}
