#!/usr/bin/env node
/**
 * `dns-doctor` — the DNS Doctor API from the terminal.
 *
 *   dns-doctor scan example.com            cached report, or a fresh scan on a miss
 *   dns-doctor scan example.com --fresh    force a fresh scan
 *   dns-doctor propagation www.example.com --type A --expect 203.0.113.10
 *   dns-doctor dmarc-upgrade example.com
 *   dns-doctor reverse-dns 203.0.113.10
 *   dns-doctor spf-audit example.com
 *
 * `--json` prints the API response verbatim (the path for scripts and agents).
 * Exit codes: 0 nothing failing · 1 a failing verdict · 2 error, incl. every
 * transient (rate limit, 402 offer, outage) — never read 2 as a verdict.
 */

import { parseArgs } from "node:util";

import { ApiError, DEFAULT_API_BASE, getJson, packageVersion, postJson } from "./api.js";
import {
  exitCodeFor,
  formatDmarcUpgrade,
  formatPropagation,
  formatReport,
  formatReverseDns,
  formatSpfAudit,
} from "./format.js";
import { COMMANDS, reportPath, routeFor } from "./routes.js";

const USAGE = `dns-doctor ${packageVersion()} — scan, fix and verify a domain's DNS (${DEFAULT_API_BASE})

usage: dns-doctor <command> <target> [options]

commands
  scan <domain>            SPF, DKIM, DMARC, MX, DNS health, expiry, blacklists — the persisted
                           report, or a fresh scan when there is none (--fresh forces one)
  propagation <name>       one name read from six locations on four continents
                           (--type A|AAAA|CNAME|MX|TXT|NS, --expect <value>)
  dmarc-upgrade <domain>   the next safe DMARC policy step as a record, or why there is none
  reverse-dns <ip>         forward-confirmed reverse DNS for a mail server address
  spf-audit <domain>       the SPF include tree with registration and lookup findings

options
  --json                   print the API response verbatim
  --fresh                  (scan) force a fresh scan instead of the cached report
  --type <rrtype>          (propagation) record type, default A
  --expect <value>         (propagation) the value the record should now hold
  --version, --help

Fix records are generated by a deterministic engine and printed verbatim; a human
approves every DNS change. Set DNSDOCTOR_API_TOKEN to raise the anonymous budget.`;

interface Parsed {
  command: string;
  target: string;
  json: boolean;
  fresh: boolean;
  type: string;
  expect: string | undefined;
}

export function parse(argv: string[]): Parsed | "help" | "version" {
  const { values, positionals } = parseArgs({
    args: argv,
    allowPositionals: true,
    options: {
      json: { type: "boolean", default: false },
      fresh: { type: "boolean", default: false },
      type: { type: "string", default: "A" },
      expect: { type: "string" },
      help: { type: "boolean", default: false },
      version: { type: "boolean", default: false },
    },
  });
  if (values.version) return "version";
  const [command, target] = positionals;
  if (values.help || !command || !target || !COMMANDS.includes(command) || command === "report") {
    return "help";
  }
  return {
    command,
    target,
    json: values.json,
    fresh: values.fresh,
    type: values.type,
    expect: values.expect,
  };
}

/** One request per command — the endpoint's own field names, nothing renamed. */
export async function run(parsed: Parsed): Promise<unknown> {
  const { command, target } = parsed;
  if (command === "scan") {
    if (parsed.fresh) return postJson(routeFor("scan").path as string, { domain: target });
    return getJson(reportPath(target));
  }
  if (command === "propagation") {
    const body: Record<string, unknown> = { name: target, record_type: parsed.type };
    if (parsed.expect !== undefined) body.expected_value = parsed.expect;
    return postJson(routeFor("propagation").path as string, body);
  }
  if (command === "dmarc-upgrade") return postJson(routeFor("dmarc-upgrade").path as string, { domain: target });
  if (command === "reverse-dns") return postJson(routeFor("reverse-dns").path as string, { ip: target });
  if (command === "spf-audit") return postJson(routeFor("spf-audit").path as string, { domain: target });
  throw new Error(`unknown command ${command}`);
}

export function render(command: string, body: unknown): string {
  if (command === "scan") return formatReport(body);
  if (command === "propagation") return formatPropagation(body);
  if (command === "dmarc-upgrade") return formatDmarcUpgrade(body);
  if (command === "reverse-dns") return formatReverseDns(body);
  if (command === "spf-audit") return formatSpfAudit(body);
  return JSON.stringify(body, null, 2);
}

export async function main(argv: string[]): Promise<number> {
  const parsed = parse(argv);
  if (parsed === "version") {
    process.stdout.write(`${packageVersion()}\n`);
    return 0;
  }
  if (parsed === "help") {
    process.stdout.write(`${USAGE}\n`);
    return argv.includes("--help") ? 0 : 2;
  }
  try {
    const body = await run(parsed);
    process.stdout.write(`${parsed.json ? JSON.stringify(body, null, 2) : render(parsed.command, body)}\n`);
    return exitCodeFor(parsed.command, body);
  } catch (error) {
    const message = error instanceof ApiError ? error.message : error instanceof Error ? error.message : String(error);
    process.stderr.write(`dns-doctor: ${message}\n`);
    return 2;
  }
}

const invokedDirectly =
  typeof process.argv[1] === "string" && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (invokedDirectly) {
  main(process.argv.slice(2)).then((code) => {
    process.exitCode = code;
  });
}
